---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-helm-installer
  namespace: argocd-helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-helm-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-helm-installer
    namespace: argocd-helm
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: argocd-helm
spec:
  source:
    sourceType: Catalog
    catalog:
      packageName: argocd-helm
      version: 7.6.6
  install:
    namespace: argocd-helm
    serviceAccount:
      name: argocd-helm-installer