apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
spec:
  priority: 0
  source:
    type: Image
    image:
      pollIntervalMinutes: 10
      ref: docker.io/perdasilva/catalog:2
